name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build . --file ./ATS.API/Dockerfile --tag atsapi:$(date +%s)
    - name: Tag Docker image
      run: docker tag atsapi:$(date +%s) ${{ secrets.DOCKER_USERNAME }}/atsapi:latest
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/atsapi:latest


